### ISSUE TITLE
Is there any way that I can erase single Path 

### ISSUE THREAD

**Issue by tianjyan82** [chillibits/drawing-activity#80]
as title.

**Comment by marcauberer** [comment]
Hi, do you mean to erase a whole line with the eraser tool?

**Comment by tianjyan82** [comment]
yes

Marc Auberer ***@***.***> 于 2021年7月8日周四 18:33写道：

**Comment by marcauberer** [comment]
Not at the moment. This feature is not supported by this third party lib, this lib is using ...
